### ISSUE TITLE
Ubuntu 12.04 problems

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#1102]
Hi!

I installed the Ubuntu 12.04 (beta 2) default emesene version, but something is wrong with it.

All widgets (status, profile information) and windows are visible or blank first and I need to wait about 10 seconds to show it normally.

screenshot: http://noob.hu/2012/03/28/emesene_bug.png

The second problem: Emesene show an indicator on panel, not in Messaging Menu.

screenshot: http://noob.hu/2012/03/28/emesene_bug2.png

**Comment by KinG-InFeT** [comment]
problem the new version the MyUnity?

**Comment by zipatei** [comment]
its true.. but aparently, now its fixed...

**Comment by rockybalboa** [comment]
Where it is fixed? In git repo or in Ubuntu 12.04?

**Comment by zipatei** [comment]
I dont know... but it fixed with last updates

**Comment by rockybalboa** [comment]
The Ubuntu default version is still wrong for me. But I don't experience this with the git version.

**Comment by rockybalboa** [comment]
And what's up with the Messaging Menu integration?

**Comment by Sbte** [comment]
Works fine for me with the latest version of 12.04. It also selects the Messaging Menu by default. I only tested the git version though. Maybe we should release a new version of emesene and do an SRU.

**Comment by rockybalboa** [comment]
I reinstalled Ubuntu 12.04, and now it is okay.
