### ISSUE TITLE
MSN custom emoticon issues

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1413]
http://imageshack.us/photo/my-images/836/msncustomemo.png/

WLM 2009 on Windows for account  A
emesene git on Linux for account B

Issue 1: A has no profile picture of B on WLM
Issue 2: B will got lots deliver error
Issue 3: B sent custom emoticon (gif/jpg...) to A but A got nothing

**Comment by moneycat** [comment]
Seems related to #1335

**Comment by c10ud** [comment]
yes, we need to look in the direct-p2p merge commits and see if there's some obvious error. e.g. i remember a line when i thought "wtf", i'll check asap

**Comment by c10ud** [comment]
#1354

**Comment by c10ud** [comment]
fixed disabling direct connect

**Comment by moneycat** [comment]
@c10ud In my case, I think this issue not really solved because WLM still cannot got the custom emoticon from emesene.

**Comment by moneycat** [comment]
After request of MSNObjectStore, when emesene <-> emesene, it will never download complete. Then in the sender's window, it arises multiple 'Error delivering message'.

For WLM -> emesene, the custom emoticon works except for my @LIVE.COM account.
