### ISSUE TITLE
Can't open View information

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#145]
Traceback (most recent call last):
  File "/home/sven/emesene/emesene/gui/gtkui/ContactMenu.py", line 51, in <lambda>
    lambda *args: self.handler.on_view_information_selected())
  File "/home/sven/emesene/emesene/gui/base/Handler.py", line 225, in on_view_information_selected
    contact.account)
  File "/home/sven/emesene/emesene/gui/gtkui/Dialog.py", line 558, in contact_information_dialog
    ContactInformation.ContactInformation(session, account).show()
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 32, in **init**
    self._create_tabs()
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 68, in _create_tabs
    self.chats = ChatWidget(self.session, self.account)
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 273, in __init__
    self.refresh_history()
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 304, in refresh_history
    self.request_chats_between(1000, self._on_chats_ready)
  File "/home/sven/emesene/emesene/gui/gtkui/ContactInformation.py", line 309, in request_chats_between
    from_day).timetuple())
ValueError: day is out of range for month

Probably because today is the 31st of October, and September (previous month) only has 30 days.

**Comment by marianoguerra** [comment]
fixed in https://github.com/emesene/emesene/commit/1689b7a8f774bcd8d6929060913d9a7a792b84ab

also made chat history work again, still need some refactoring to remove the msn dependent code but it works

**Comment by Sbte** [comment]
Still doesn't work for me. Is this because I'm using papyon, or is there something I should do to make it work (like removing the db)?

**Comment by marianoguerra** [comment]
do you get an error or something?

someone else using papyon to test the contact history?

**Comment by Sbte** [comment]
Only 

TypeError: can't convert return value to desired type
TypeError: can't convert return value to desired type
*\* Message: console message: undefined @1: ReferenceError: Can't find variable: scrollToBottom

When opening view information, like I said in the other bug report about this issue. 

Other than the chat history, the other histories are blank too for most contacts. For some the Nick history or Message history works, but for most it doesn't. I don't have anyone with the other histories working.

**Comment by marianoguerra** [comment]
it didn't worked because it wasn't implemented, I puished the implementation a minute ago, update and test.

**Comment by Sbte** [comment]
Ah. Seems to work now. The messages I received before are gone (obviously, because it wasn't implemented), but what I received just now seems to work just fine. Thanks :D
