### ISSUE TITLE
Message text doesent appear in message window

### ISSUE THREAD

**Issue by MaxPayneFH** [emesene/emesene#1520]
I'm running emesene  on Ubunto 12.04 and the messages I receive or send dont apear on the message window, but I can see them when I'm writing them and I also see them writen in the notifications I receive.

**Comment by Sbte** [comment]
Any errors when you run emesene from a terminal?

**Comment by MaxPayneFH** [comment]
I get this output when I run emesene via terminal:

_Error: Can't connect to Snarl._
Traceback (most recent call last):
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 68, in idle_state
    self.timer = extension.get_and_instantiate('idle timer')
  File "/usr/share/emesene/emesene/extension.py", line 621, in get_and_instantiate
    return extension_manager.get_and_instantiate(category_name, _args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 492, in get_and_instantiate
    return category.get_and_instantiate(_args, *_kwargs)
  File "/usr/share/emesene/emesene/extension.py", line 310, in get_and_instantiate
    inst = cls(_args, *_kwargs)
  File "/home/max/.config/emesene2/plugins/idle_status/xidletimer.py", line 39, in **init**
    self.xss        = ctypes.cdll.LoadLibrary('libXss.so')
  File "/usr/lib/python2.7/ctypes/**init**.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: libXss.so: cannot open shared object file: No such file or directory

**Comment by moneycat** [comment]
`OSError: libXss.so: cannot open shared object file: No such file or directory` Your system lost this file which is xidletimer need.
First, you can check if this issue occurs after disabling the idle timer extension.
Second, to check is there any update of the extension or  to install the lost library.

**Comment by Sbte** [comment]
This is definitely an old version of the idle_status plugin. It should be fixed in the latest version. Emesene will automatically check for plugin updates when using 2.12.9, or you could also go to Preferences->Updates.

**Comment by MaxPayneFH** [comment]
I can't disable the idle status plugin, it just cant be unchecked, all other plugin can but that one just won't, don't know why.
libXss is installed or so says synaptic, I did reinstall it and emesene aswell but still no text in the messages :S

I can't update extensions, when I refresh the page nothing happens or when I use the download button I get a refreshing extensions bar at 0% that disappears right away.

**Comment by MaxPayneFH** [comment]
I got even more errors on terminal now : /

[23:51:01 WARNING papyon.p2p] Trying to publish an empty MSNObject
_Error: Can't connect to Snarl._
[23:51:02 WARNING papyon.p2p] Trying to publish an empty MSNObject
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined
Traceback (most recent call last):
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 67, in on_toggled
    self.on_stop(name)
  File "/usr/share/emesene/emesene/gui/gtkui/PluginWindow.py", line 95, in on_stop
    pluginmanager.plugin_stop(name)
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 225, in plugin_stop
    self._plugins[name].stop()
  File "/usr/share/emesene/emesene/e3/common/pluginmanager.py", line 136, in stop
    self._instance.stop()
  File "/home/max/.config/emesene2/plugins/idle_status/plugin.py", line 65, in stop
    extension.unregister('idle timer', LinuxTimer)
NameError: global name 'LinuxTimer' is not defined

**Comment by moneycat** [comment]
Try to delete it directly from your home directory/.config/emesene2/plugins

**Comment by Sbte** [comment]
That last thing should probably be fixed. LinuxTimer is indeed undefined. Will do that in a moment

**Comment by Sbte** [comment]
Fixed in the plugins repo.

**Comment by MaxPayneFH** [comment]
I did delete the idle status plugin from /.config/emesene2/plugins but the bug still persisted so I deleted the whole folder and reinstalled emesene.

The bug is finally gone.

Thanks for the help
