### ISSUE TITLE
Conversation Toolbar

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#227]
Just a mild annoyance, but if I move the conversation toolbar (up/down), I just reverts to the default position when the conversation is restarted. It doesn't effect functionality but it's an important aesthetic element that bother me and most likely others.

**Comment by c10ud** [comment]
confirmed

**Comment by Sbte** [comment]
Fixed by commit f69ff720f79d66621f2081585f4feb39e7be5c31 ?

**Comment by c10ud** [comment]
didn't try, but i guess we can safely close -- reopen if issue persists
