### ISSUE TITLE
Link incomplete in conversation

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#240]
The link does not appear complete. Look at the picture example:

http://img87.imageshack.us/img87/9595/capturaecra3.png

**Comment by c10ud** [comment]
fixed by sbte

**Comment by zipatei** [comment]
Not Fixed.

http://img339.imageshack.us/img339/5008/capturaecra4q.png

**Comment by Sbte** [comment]
No clue then. It works fine over here. Maybe you could give the exact text that you used?

**Comment by zipatei** [comment]
http://www.pai.pt/detailssearch.ds?detailsListingId=y:PT_96394153_9999_4__1&adrecip=chatbot

**Comment by Sbte** [comment]
Ah, the & was recognised as part of a special html character, that shouldn't be parsed by the emoticon converter. Sent a patch in which it's recognised as part of the url.

**Comment by Sbte** [comment]
Should be fixed now

**Comment by zipatei** [comment]
yes... fixed... thanks
