### ISSUE TITLE
gobject deprecation warning

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#334]
emesene2/emesene/gui/gtkui/Avatar.py:102: DeprecationWarning: integer argument expected, got float
  gobject.timeout_add(timeBetweenFrames, self.animate_callback)

**Comment by Sbte** [comment]
This is because of b3d245017abf4f092735df896e032aafe3da23e2

New divisions automatically convert to floats.

**Comment by marianoguerra** [comment]
fixed

**Comment by marianoguerra** [comment]
fixed

**Comment by marianoguerra** [comment]
fixed

**Comment by marianoguerra** [comment]
it seems I fixed it :P (damn internet connection)

**Comment by zipatei** [comment]
/home/andre/emesene/emesene/gui/gtkui/Renderers.py:538: DeprecationWarning: integer argument expected, got float
  rect, index, index + 1))

Not fixed...

**Comment by marianoguerra** [comment]
that's a different warning.

fixed on my repo
