### ISSUE TITLE
Issues with setting an empty personal message

### ISSUE THREAD

**Issue by Mystro256** [emesene/emesene#438]
I was going to set my personal message, which was nothing at the time when I signed in, and when I click on the "Click here to set your message" text, instead of a blank text box, it appears my personal message was actually: "[C=#969696][I]Click here to set your message[/I][/C]" instead of nothing.

It's an obvious glitch that seems to happen if I sign in with a blank message from a previous sign in. As well it seems if I erase my person message, the "Click here to set your message" message is no longer there.

**Comment by Sbte** [comment]
Already reported in #430. I think arielj is working on a fix.

**Comment by arielj** [comment]
this should already be fixed, update your fork

**Comment by ghost** [comment]
The second part of this wasn't included in #430, and wasn't fixed you commit. If you erase the personal message, it does not show "Click here to set your message" until you disconnect and reconnect.

**Comment by arielj** [comment]
just commited a fix for this

**Comment by Mystro256** [comment]
Yep, arielj's commit made it work

**Comment by ghost** [comment]
@Mystro256 see https://github.com/arielj/emesene/commit/e770d644b44be85630b2ab83524b4e5a1653ba81 .

**Comment by Mystro256** [comment]
opps sorry, I missed that :S
