### ISSUE TITLE
GTK skins using gradients show a demarcation around avatars

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#452]
See this picture for more information:
http://img827.imageshack.us/img827/6426/proofbl.jpg
Basically, emesene doesn't mix very well with gradients.

**Comment by c10ud** [comment]
they're bugs in gtk themes, actually -- iirc we have been able to workaround them in emesene1, but still, they're bugs in themes

**Comment by c10ud** [comment]
@arielj did you workaround this once, am i right?

**Comment by arielj** [comment]
I can't see the image, it says "domain unregistered" and only shows imageshack's frog

For the description, I think I fixed something similar for the tiny arrow that hides the avatars on emesene1, but that time it was caused by the arrow being drawn inside a DrawingArea widget. I haven't look the actual code, I don't know if it's the same bug, I'll check that when I get some time!

**Comment by sm-Fifteen** [comment]
@arielj
That's odd, I can still see the image, personally...
Can you suggest anywhere I could reupload it?

**Comment by arielj** [comment]
freeimagehosting.net or any other image hosting site

**Comment by sm-Fifteen** [comment]
http://www.freeimagehosting.net/uploads/7e969c687d.jpg
How about that?

**Comment by arielj** [comment]
Just commited a fix for this, I think it's fixed but please test it with your gradiented theme (I've tested with some hacked color, but not with gradient themes).

**Comment by sm-Fifteen** [comment]
I'd love to tell you that it works, but unfortunately...
http://www.freeimagehosting.net/uploads/d6eebb22d3.jpg
...it doesn't.

**Comment by c10ud** [comment]
did you apply the fix? its' not in emesene/master yet

2011/5/4 Riboshom
reply@reply.github.com:

**Comment by c10ud** [comment]
ok i pulled the fix in emesene/master so you can test...try updating now

2011/5/4 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by sm-Fifteen** [comment]
I confirm, it's been fixed!
