### ISSUE TITLE
Papyon does not seem to be capable of handling the removal of an avatar

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#471]
/home/andre/emesene/emesene/gui/gtkui/**init**.py:102: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
[03:51:05 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable

Edit (Sbte): 

Summary:

Papyon doesn't seem to be able to handle someone not having an avatar, and there also doesn't seem to be a way to remove the avatar.

Also edited the title

**Comment by c10ud** [comment]
uhm, what were you doing?

**Comment by zipatei** [comment]
papylib not recognize my profile without avatar (avatar = none)

**Comment by c10ud** [comment]
you mean you had a profile with nickname, message and None DP?

did it get the nick and the message?

**Comment by zipatei** [comment]
I'm here trying to be simple in my English (very poor) and i failed miserably. :p

A good way to check this problem is to do the following:
1. Go Preferences >> live messenger
2. remove image and save.
3. open emesene

Result: Emesene not recognize new "none" avatar and this errors:

[03:51:05 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable

**Comment by c10ud** [comment]
well, if you removed the avatar you have it == None.. If this doesn't break anything it's just a matter of checking if is None when trying to save, i think

**Comment by zipatei** [comment]
The problem is that emesene fails to recognize that my avatar == none. Therefore does not update my avatar.

And then, even if you want to change my avatar (again for any picture), just going back to live messenger, and put a new image in order to change the avatar in emesene.

**Comment by c10ud** [comment]
oh, so you mean you have None avatar but emesene shows some other avatar?

**Comment by zipatei** [comment]
Exactly.

**Comment by c10ud** [comment]
now that i think of it, is it even possible to remove the pic? i'm digging into the code and it doesn't seem that easy (i mean, talking of msn protocol) :s

**Comment by zipatei** [comment]
I removed the profile picture on live messenger. 

Emesene is that it seems not to recognize. Even "no picture" button does not work in Avatar Chooser.

**Comment by Sbte** [comment]
It's not so easy to do it with papyon at least. See #479

**Comment by c10ud** [comment]
ok, let's refer to this issue only

**Comment by c10ud** [comment]
ok now i just need to see if we can remove the picture from content roaming

**Comment by c10ud** [comment]
ok, now it's a papyon issue: if i ask to store an empty avatar in content_roaming

papyon/service/contentroaming/storage.py

```
    photo = expression_profile.find('./st:Photo')
    if photo is not None:
        photo_rid = photo.findtext('./st:ResourceID')
        document_stream = photo.find('./st:DocumentStreams/st:DocumentStream')
        photo_mime_type = document_stream.findtext('./st:MimeType') <<<<<<<<<excepts here
        photo_data_size = document_stream.findtext('./st:DataSize', "int")
        photo_url = document_stream.findtext('./st:PreAuthURL')
    else:
        photo_rid = photo_mime_type = photo_data_size = photo_url = None
```

**Comment by c10ud** [comment]
for now i won't add the call otherwise it will except to everyone:

just change papylib/Worker.py:

[---]

EDIT: don't do this change as it will break your profile

**Comment by c10ud** [comment]
it must be properly fixed in papyon with some new SOAP request

**Comment by c10ud** [comment]
reported upstream https://bugs.freedesktop.org/show_bug.cgi?id=40542

**Comment by zipatei** [comment]
This not fixed yet, right?

[14:21:40 ERROR papylib.Events] Writing of content roaming picture failed: 'NoneType' object is not iterable

**Comment by Sbte** [comment]
Well, it works right? That error should be harmless (I hope).

**Comment by zipatei** [comment]
Not yet. Because it is still not possible to set a picture on emesene and take the same profile.

**Comment by Sbte** [comment]
What?

**Comment by zipatei** [comment]
:) lol. sorry my english.

Reproduce:
1. Avatar chooser
2. Set my avatar

Emesene have a picture, but my profile not.

**Comment by Sbte** [comment]
Oh, you mean your live profile. Well, that's not what this bugs is about...

Anyhow, I'm not even sure if we're supposed to (be able to) set the profile picture. As long as it's used in msn right?

**Comment by zipatei** [comment]
Yes.

But for example. I have a picture on emesene. But others can not see it.

**Comment by Sbte** [comment]
That's a broken profile. Anyhow, if you have more questions, don't do it here, because this bug is about REMOVING your avatar. So not having a picture on purpose. Which is the opposite of what you want.

**Comment by zipatei** [comment]
look at that profile is not broken. You can make this experience with your account.
Reproduced:
- In live profile, remove your photo.
- Go to emesene and tries to set a photo.

Can not do it. It will give you the same error.
