### ISSUE TITLE
Add contact to group

### ISSUE THREAD

**Issue by 4brunu** [emesene/emesene#543]
Hello,

I have note an issue that it's present since a long time ago.

If I add a contact ou accept a friend that add me, the contact will never appear oline, and i will not be able to speak with him.

Cumps

**Comment by arielj** [comment]
Do you or your contact have a non standard domain? (not an hotmail/msn/live mail)

Does it happen with EVERY contact? or only one? is it shown using other clients?

**Comment by c10ud** [comment]
i think with current git master there could be an issue when adding a new contact and choosing a group for it. for now it's safer to just add without choosing a group and move the contact later

**Comment by 4brunu** [comment]
Just in msn, with a gmail acount, happens with every contacts

**Comment by el-dias** [comment]
I use the lastest git and the add contact dont work for me =(

**Comment by c10ud** [comment]
also #735

we must fix add_contact_to_group in papylib

**Comment by c10ud** [comment]
i tried briefly and with NO GROUP selected it seems to work ~100%

if we use add_contact_to group there's some weird papyon bug, sometimes it works sometimes not and it gives a weird:
Client got an error handling addressbook: 4 Address Book error (MemberDoesNotExist): Member does not exist

**Comment by c10ud** [comment]
pidgin seems to be affected by this bug too, microsoft is telling us that perfectly valid emails are invalid contacts..

**Comment by c10ud** [comment]
if someone wants to provide some wireshark'd SOAP requests of contact being added from WLM it could be nice so we can compare them to papyon's

**Comment by c10ud** [comment]
could be fixed in https://github.com/emesene/papyon if someone could test it.....

**Comment by hiunnhue** [comment]
"Test" means using the latest 2.11.9-devel to add a contact?

I did, and the error message seems a little bit different, not "MemberDoesNotExist"

```
[02:41:55 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
[02:41:55 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[02:41:55 ERROR papylib.Events] Error adding a contact to a group: (AddressBookError(),)
[02:41:55 ERROR papylib.Events] Client got an error handling addressbook: 4 Address Book error (ContactIdOrQuickNameRequired): This function requires ContactId or quick name contact.contactId is Empty and contact.contactInfo is null
```

**Comment by c10ud** [comment]
yes, but with the papyon i linked

2011/9/1 hiunnhue
reply@reply.github.com:

**Comment by hiunnhue** [comment]
I've done some tests again.

I post my procedure here, in case I did something wrong...

Step:
1. Get a new emesene copy from git
2. Open home/user/emesene/ and git submodule init && git submodule update
3. Open home/user/emesene/.../papylib/papyon/
     and git remote add emesene-papyon git://github.com/emesene/papyon.git
     then git pull emesene-papyon master.
4. run emesene
5. add a contact
- [Test A] using a hotmail.com account to add yahoo.com.tw contact (no group)
  Result: The contact is added to the list but off-line and unable to talk with. And the contact doesn't get any notification.

terminal:

```
[04:27:52 ERROR papylib.Events] contact xxxxxxxxxx@yahoo.com.tw not found on address book
```

debug:

```
(04:32:33) papyon.transport:>>> UUM 23 xxxxxxxxxx@yahoo.com.tw 1 1
    Dest-Agent: 'client'\r\n
    Content-Type: 'text/plain; charset=utf-8'\r\n
    \r\n
    testtesttesttest
```
- [Test B] using a hotmail.com account to add yahoo.com.tw contact (into a group)
  Result: The contact is not added, and doesn't got any notification.

terminal:

```
[04:38:09 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from contacts.msn.com:80
[04:38:09 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[04:38:09 ERROR papylib.Events] Error adding a contact to a group: (AddressBookError(),)
[04:38:09 ERROR papylib.Events] Client got an error handling addressbook: 4 Address Book error (ContactIdOrQuickNameRequired): This function requires ContactId or quick name This function requires ContactId or quick name contact.contactId is Empty and contact.contactInfo is null
```
- [Test C] using a yahoo.com.tw account to add a hotmail.com contact (no group)
  Result: The contact is added to the list but off-line and unable to talk with. And the contact doesn't get any notification.
- [Test D] using a yahoo.com.tw account to add a hotmail.com contact (into a group)
  Result: The contact is not added, and doesn't got any notification.

**Comment by c10ud** [comment]
thanks for testing, anyway is the yahoo.com.tw contact a Passport one or it's like the external yahoo im contacts?

anyway, seems like these issues aren't solved by that branch, unfortunately

**Comment by hiunnhue** [comment]
That yahoo account is a ms-passport one.

**Comment by zipatei** [comment]
Not fixed yet...

This Vodafone account is a mspassport.

[10:19:26 ERROR papyon.gnet.HTTP] Received error code 500 (Internal Server Error) from local-bay.contacts.msn.com:443
[10:19:26 WARNING papyon.service] Transport Error : HTTP Error (500): Internal Server Error
[10:19:26 ERROR papylib.Events] Error adding a contact to a group: (AddressBookError(),)
[10:19:26 ERROR papylib.Events] Client got an error handling addressbook: 4 Address Book error (ContactIdOrQuickNameRequired): This function requires ContactId or quick name contact.contactId is Empty and contact.contactInfo is null

**Comment by c10ud** [comment]
the service soap are correct, i'm closing this issue because there's little we can do it about it (server errors...)

end-of-year housekeeping!
