### ISSUE TITLE
Signals that are not unsubscribed

### ISSUE THREAD

**Issue by Sbte** [emesene/emesene#727]
Wrote as small script that checks the code for subscribed signals that are not unsubscribed. I don't have time right now to actually fix them, but for anyone who want to have some fun with them: knock yourself out. Should be quite trivial.

<del>emesene/e3/common/notification.py</del>

<del></del>

<del>self.session.signals.conv_message</del>

<del>self.session.signals.contact_attr_changed</del>

<del>self.session.signals.mail_received</del>

<del>self.session.signals.filetransfer_completed</del>

<del>self.session.signals.filetransfer_canceled</del>

<del>self.session.signals.filetransfer_invitation</del>

<del></del>

emesene/test/e3_example.py

signals.login_succeed
signals.login_failed
signals.contact_list_ready
signals.conv_first_action
signals.conv_started
signals.conv_message

<del>emesene/gui/base/ContactList.py</del>

<del></del>

<del>self.session.config</del>

<del>self.session.signals.contact_attr_changed</del>

<del>self.session.signals.picture_change_succeed</del>

<del>self.session.signals.contact_add_succeed</del>

<del>self.session.signals.contact_remove_succeed</del>

<del>self.session.signals.group_add_contact_succeed</del>

<del>self.session.signals.group_remove_contact_succeed</del>

<del>self.session.signals.contact_block_succeed</del>

<del>self.session.signals.contact_unblock_succeed</del>

<del>self.session.signals.group_add_succeed</del>

<del>self.session.signals.group_remove_succeed</del>

<del>self.session.signals.group_rename_succeed</del>

<del></del>

emesene/gui/qt4ui/Conversation.py

self.session.signals.contact_attr_changed
self.session.signals.filetransfer_invitation
self.session.signals.filetransfer_accepted
self.session.signals.filetransfer_progress
self.session.signals.filetransfer_completed

emesene/gui/qt4ui/TrayIcon.py

self._handler.session.signals.status_change_succeed

emesene/gui/qt4ui/pages/MainPage.py

session.signals.profile_get_succeed
session.signals.status_change_succeed

emesene/gui/qt4ui/pages/ConversationPage.py

self.session.signals.contact_attr_changed

emesene/gui/qt4ui/widgets/ContactListProxy.py

config
config
config
config
config

emesene/gui/qt4ui/widgets/ContactListDelegate.py

self._config
self._config

emesene/gui/qt4ui/widgets/ContactListModel.py

config
config
config
config
config

<del>emesene/gui/gtkui/MainWindow.py</del>

<del></del>

<del>self.session.signals.contact_attr_changed</del>

<del>self.session.signals.mail_count_changed</del>

<del></del>

<del>emesene/gui/gtkui/Indicator.py</del>

<del></del>

<del>self.handler.session.signals.status_change_succeed</del>

<del></del>

<del>emesene/gui/gtkui/TabWidget.py</del>

<del></del>

<del>self.session.config</del>

<del></del>

<del>emesene/gui/gtkui/Preferences.py</del>

<del></del>

<del>self.session.config</del>

<del>self.session.config</del>

<del>self.session.config</del>

<del>self.session.config</del>

<del>self.session.config</del>

<del>self.session.config</del>

<del></del>

<del>emesene/gui/gtkui/TrayIcon.py</del>

<del></del>

<del>self.handler.session.signals.status_change_succeed</del>

<del>self.handler.session.signals.conv_message</del>

<del>self.handler.session.signals.message_read</del>

<del>self.handler.session.signals.contact_attr_changed</del>

**Comment by Sbte** [comment]
Oh, if you guys think my script could be improved, just tell.

**Comment by pepeleproso** [comment]
emesene/gui/gtkui/MainWindow.py
 self.session.signals.contact_attr_changed
 self.session.signals.mail_count_changed

done

**Comment by c10ud** [comment]
ok, only 

emesene/gui/base/ContactList.py
and
emesene/gui/gtkui/Preferences.py

if we want a good gtk..Sbte i don't see your script neither the other changes you did to test proper destruction of conversations :D

**Comment by Sbte** [comment]
@pepeleproso, you missed the config one in ContactList.py

@c10ud: That's because it's a total mess?

I'll make a git tree with tools and also move my emesene-statistics too there. And no, I won't make it in the emesene account because I'm can't because I'm not an owner. :)

**Comment by Sbte** [comment]
https://github.com/Sbte/emesene-tools

**Comment by c10ud** [comment]
transfer ownership to emesene! NAO!

(you can now hax github emesene)

2011/7/15 Sbte reply@reply.github.com:

**Comment by Sbte** [comment]
Sir, yes sir. Done sir.

**Comment by Sbte** [comment]
Nice work Jose. Gtk is done now. 

I'll just close this issue since qt4 is still a work in progress.

@Whisky84, please fix them though ;)
