### ISSUE TITLE
[Feature Request] Ubuntu (new) message menu support

### ISSUE THREAD

**Issue by ricsipontaz** [emesene/emesene#745]
Hi all!

In Oneiric (Ubuntu 11.10 - development version) there is a new message menu, which isn't supported by emesene yet. Any chance to somebody change this?

Screenshot:

http://stock4.pho.to/data10/7/1/c/71c9027a-bea9-32a4-3d6c-1ff971bcf074.png

**Comment by Sbte** [comment]
<i>hates Ubuntu for not having backward compatibility.</i>

I'll see if I can install Oneiric in a VM or something. But not now.

**Comment by ricsipontaz** [comment]
Okay, thanks.

**Comment by Sbte** [comment]
I run into this https://bugs.launchpad.net/ubuntu/+source/xorg-server/+bug/811355

I'm subscribed to the bug, so once it's fixed, I'll look into it. Until then, not a chance.

**Comment by c10ud** [comment]
[21:22] <c10ud> 21:21] <tedg> This is the new package: indicator-status-provider-emesene

so, installing this package should fix the issue, we must remember to tell our ubuntu packager to add a dep on this next time emesene is uploaded to oneiric :)

**Comment by Sbte** [comment]
Ok, my x bug was already fixed. Downloading that package didn't seem to do anything however. jcastro doesn't know what he's talking about ;)

**Comment by Sbte** [comment]
Actually, I take that back. It seems to work after reboot (why's that even needed?). The Invisible == Offline issue is still there however.

**Comment by c10ud** [comment]
i've been said the source of that package is 1 c file, you may want to
submit a patch?

2011/7/28 Sbte reply@reply.github.com:

**Comment by ricsipontaz** [comment]
Thanks!
