### ISSUE TITLE
Windwos 2.11.9 version, plugins download -> freeze

### ISSUE THREAD

**Issue by mikk73** [emesene/emesene#908]
2.11.9 official or latest git version, portable or installer version or run directly source from pythonw
1. Start emesene2 portable (debug exe)
2. Data is filled, click to connect.
3. Option/preferences/plugins. List is updated, this works.
4. I select this: "contact status history combo" or any, click to download. "Downloading extensions" window is appear.
5. FREEZE

Freeze mean this (Sbte read pls):
Apllication has out of control. I click to anywhere on emesene2 window, nothing happen. If I click on "Downloading extensions" window cancel button, nothing happen. I need taskmenager the kill this app or emesene2 try icon, quit menu.

debug window this:

```
No handlers could be found for logger "emesene.e3.common.DBus"
c:\emesene\emesene-2.11.8-devel-20111102_0912-portable\.\e3\jabber\Worker.py:27:
 DeprecationWarning: the sha module is deprecated; use the hashlib module instea
d
c:\emesene\emesene-2.11.8-devel-20111102_0912-portable\.\gui\gtkui\__init__.py:8
9: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
[09:51:48 WARNING pluginmanager] error importing "contact_status_history_combo":
 No module named contact_status_history_combo
Traceback (most recent call last):
  File "gui\gtkui\utils.pyo", line 260, in check

  File "gui\gtkui\ExtensionList.pyo", line 283, in show_update_callback

  File "gui\gtkui\PluginWindow.pyo", line 69, in on_update

  File "pluginmanager.pyo", line 252, in plugin_description

  File "pluginmanager.pyo", line 156, in get_description

AttributeError: 'NoneType' object has no attribute 'Plugin'
```

x
6. Start again emesene2 (debug)
7. Data is filled, click to connect.
8. Option/preferences/plugins. Plugins window is now empty. If I click to refresh button, nothing change.

Debug window:

```
No handlers could be found for logger "emesene.e3.common.DBus"
c:\emesene\emesene-2.11.8-devel-20111102_0912-portable\.\e3\jabber\Worker.py:27:
 DeprecationWarning: the sha module is deprecated; use the hashlib module instea
d
[10:01:28 WARNING pluginmanager] error importing "contact_status_history_combo":
 No module named contact_status_history_combo
c:\emesene\emesene-2.11.8-devel-20111102_0912-portable\.\gui\gtkui\__init__.py:8
9: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
[10:01:32 WARNING pluginmanager] error importing "contact_status_history_combo":
 No module named contact_status_history_combo
Traceback (most recent call last):
  File "gui\gtkui\Preferences.pyo", line 226, in _on_row_activated

  File "gui\gtkui\Preferences.pyo", line 231, in showPage

  File "gui\gtkui\PluginWindow.pyo", line 69, in on_update

  File "pluginmanager.pyo", line 252, in plugin_description

  File "pluginmanager.pyo", line 156, in get_description

AttributeError: 'NoneType' object has no attribute 'Plugin'
[10:01:42 WARNING pluginmanager] error importing "contact_status_history_combo":
 No module named contact_status_history_combo
Traceback (most recent call last):
  File "gui\gtkui\PluginWindow.pyo", line 69, in on_update

  File "pluginmanager.pyo", line 252, in plugin_description

  File "pluginmanager.pyo", line 156, in get_description

AttributeError: 'NoneType' object has no attribute 'Plugin'
```

If I run emesene from python, see latest git:

```
git clone https://github.com/emesene/emesene.git
cd emesene
git reset --hard v2.11.7
git reset --hard v2.11.9
git submodule init
git submodule update
```

```
python emesene.py
```

Symtomps is equally, app is freeze when download plugin, this is not exe problem.

Debug window:

```
No handlers could be found for logger "emesene.e3.common.DBus"
c:\Temp\emesene\emesene\e3\jabber\Worker.py:27: DeprecationWarning: the sha modu
le is deprecated; use the hashlib module instead
  import sha
c:\Temp\emesene\emesene\gui\gtkui\__init__.py:89: Warning: g_object_set_qdata: a
ssertion `G_IS_OBJECT (object)' failed
  gtk.main()
```

ps.:
Theme download too bad. Download is success, I select new theme, but after emesene is restart and connect, emesene windows is empty.

**Comment by Sbte** [comment]
You could add some prints to e3/common/Collections.py save_files, and see where it hangs. But before that, you could try to remove the contact_status_history_combo dir from your config dir. That's what's causing the error I think.

**Comment by mikk73** [comment]
Hi!
Collections.py is python file. This is not save file. 
"add some prints" - what is this?
I don't know what u need.

**Comment by Sbte** [comment]
That is what downloads the files. It's in the emesene folder, e3/common/Collections.py function save_files.

You could add something like print "test" at some places in the function to see what isn't being reached. That's where the hang happens.

**Comment by mikk73** [comment]
This is clean.

With latest git version, I try download "idle_status" plugin, result: http://www.megaupload.com/?d=4V406EF4

... after freeze :)

**Comment by Sbte** [comment]
Ok, so it successfully downloads all the files. So that's not the problem. Maybe it's a bug in GtkRunner

Note to self: remove `self.on_update(clear=True)`

**Comment by mikk73** [comment]
Okay, this string found in: \gui\gtkui\ExtensionList.py
But more results found not only one!

Okay, I try mod this:

```
def download(self):
        '''download an extension'''
        thc_cur = self.thc_com[self.thc_cur_name]
        thc_cur.download(self.download_item)
        #self.on_update(clear=True)
```

Okay, plugins download now works, and plugin is works, example old status combo.

Next problem, theme download. Now its works too. But if I select theme (theme/image theme) need extensions, redraw main screen button click, to apply new theme.

But theme download not works correctly always, sometimes no files download, this cause empty main screen if I click redraw. I think need additional code in emesene2, if not all (theme) files found, then theme is disabled. Or check downloaded files, compare, checksum etc.

Next problem, if I select theme, and click download, but I click cancel under download, incomplete theme is selectable (!), this cause empty screen too. (Interesting, in linux version if I click cancel under theme download, all new downloaded theme is unselectable).

Ok, topic problem is about solved, but not 100% at the moment.

ps.: msn protocol is not working in emesene1 & 2

**Comment by Sbte** [comment]
Ah, I'll push that fix first. Then I'll look into the theme download stuff. Thanks for helping us improve emesene!

**Comment by Sbte** [comment]
Found the second issue too. It tries to delete the whole themes folder...

**Comment by Sbte** [comment]
I think I fixed all your issues. Please try with current master.

**Comment by mikk73** [comment]
Hi!

"Master" what is this. I'm not developer here. Okay, I found this: https://github.com/emesene/emesene
Current branch: Master
zip file is: emesene-emesene-v2.11.9-82-gbd292d5.zip
Interest, zip file and git clone method result is different. I see your modification in "e3/common/Collections.py", and I see, zip file is the right version. I uses this. But why different? LOL.

Okay, unzip zip file, copy xmppy module... (because this is always missing). After start, first look, xmppy module not activated, because only "msn" and "dummy" protocol selectable.
"git submodule init" and "git submodule update" not working, because this is unzipped file, not git package with this command:
`git clone https://github.com/emesene/emesene.git`

Plugin download working, plugin is working.
Theme download is working, but problem is stay, if I click cancel button under download, theme is incomplete, and selectable, this is cause empty screen after redraw or restart.

But good news, msn is working.

**Comment by Sbte** [comment]
`git pull origin master`? Does that help for the fact that apparently for you master is different from the zip? If you do that you wouldn't have to download xmpp every time either.

About the issue: cancelling plugin downloads is working right?

**Comment by mikk73** [comment]
Hi!

"git pull origin master" I dont know what is this. I never uses git before.

My first lines in batch file, these, if I want download git version:

```
git clone https://github.com/emesene/emesene.git
cd emesene
git reset --hard v2.11.7
git reset --hard v2.11.9
git submodule init
git submodule update
```

These lines from here: https://github.com/emesene/emesene/wiki/Windows-%28New%29

If you know any commands, which download current master from git, please write me exactly.

"cancelling plugin downloads is working right?"

I wrote already in my last message: "but problem is stay, if I click cancel button under download, theme is incomplete, and selectable, this is cause empty screen after redraw or restart."

**Comment by Sbte** [comment]
Themes, but what about plugins? Are the both broken or only the themes?

Also, next time you need emesene, you could just do this, as long as the directories from the previous clone are still there of course.

```
cd emesene
git pull origin master
```

**Comment by mikk73** [comment]
Hi!

Okay, this command is working, and update my emesene git directory from "master".

New batch file this:

```
rm -rf emesene
git clone https://github.com/emesene/emesene.git
cd emesene
git reset --hard v2.11.7
git reset --hard v2.11.9
git submodule init
git submodule update
git pull origin master
```

But nothing change, only "msn" and "dummy" protocol selectable. This is not my problem I think :)

"Themes, but what about plugins? Are the both broken or only the themes?"

I wrote already too: "Plugin download working, plugin is working.". You don't see my lines? :)

I can download all plugin without problem. Now I try cancel under plugin download... this is cause: FREEZE.

```
C:\Temp>cd emesene/emesene

C:\Temp\emesene\emesene>python emesene.py
No handlers could be found for logger "emesene.e3.common.DBus"
[20:23:50 WARNING e3.common.Config] couldn't load config: C:\Documents and Settings\mikk\Application Data\emesene\emesene2\dummy.server.com\test\config (no file)
C:\Temp\emesene\emesene\gui\gtkui\__init__.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
  gtk.main()
Traceback (most recent call last):
  File "C:\Temp\emesene\emesene\gui\gtkui\utils.py", line 260, in check
    self.callback(result)
  File "C:\Temp\emesene\emesene\gui\gtkui\ExtensionList.py", line 282, in show_update_callback
    self.on_update(clear=clear)
  File "C:\Temp\emesene\emesene\gui\gtkui\PluginWindow.py", line 69, in on_update
    description=pluginmanager.plugin_description(name)),
  File "C:\Temp\emesene\emesene\pluginmanager.py", line 252, in plugin_description
    return self._plugins[name].get_description()
  File "C:\Temp\emesene\emesene\pluginmanager.py", line 156, in get_description
    description = self.module.Plugin.description
AttributeError: 'module' object has no attribute 'Plugin'
```

Much easy, I recommend for U, use OS emulator, example free virtualbox on your OS, and install windows... :)

**Comment by Sbte** [comment]
Fixed!

**Comment by mikk73** [comment]
Hi!

Yes, cancel under download is now working, cancelled theme is unselectable, good.

But still only msn and dummy protocol selectable, jabber is not working.

**Comment by Sbte** [comment]
Yes, that doesn't work under linux either atm...

**Comment by Sbte** [comment]
See #918

**Comment by mikk73** [comment]
Hi, with latest master, other protocol is selectable this is good, jabber is working again.

But bad news: I create exe from source, and created exe plugin/theme download is bad again, no downloaded file. Running source from python, no problem.

Example, config dir erased, start emesene2.exe, download gnome theme, select this, after I click redraw. Screen is empty. Log:

```
No handlers could be found for logger "emesene.e3.common.DBus"
Django module not found.
[02:39:41 WARNING e3.common.Config] couldn't load config: C:\Documents and Settings\mikk\Application Data\emesene\emesene2\dummy.server.com\test\config (no file)
C:\Program Files\emesene2\.\gui\gtkui\__init__.py:89: Warning: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
[02:39:53 ERROR gtkui.ExtensionList] unknown encoding: idna
[02:39:59 WARNING gui.base.ImageThemes] image theme incomplete
[02:39:59 WARNING e3.common.Signal] Signal handler (on_login_succeed.on_login_succeed) error: 'str' object has no attribute 'copy'
Traceback (most recent call last):
  File "e3\common\Signal.pyo", line 66, in emit
  File "e3\common\Signal.pyo", line 115, in __call__
  File "emesene.py", line 569, in on_login_succeed
  File "emesene.py", line 465, in draw_main_screen
  File "gui\base\Theme.pyo", line 82, in set_theme
  File "gui\base\ThemesManager.pyo", line 91, in get_theme
  File "gui\base\ImagesThemes.pyo", line 52, in get
  File "gui\base\ImageTheme.pyo", line 77, in __init__
  File "gui\base\ImageTheme.pyo", line 144, in load_information
AttributeError: 'str' object has no attribute 'copy'
[02:39:59 WARNING e3.common.Signal] Signal handler (on_contact_list_ready.on_contact_list_ready) error: 'NoneType' object has no attribute 'contact_list'
Traceback (most recent call last):
  File "e3\common\Signal.pyo", line 66, in emit
  File "e3\common\Signal.pyo", line 115, in __call__
  File "emesene.py", line 665, in on_contact_list_ready
AttributeError: 'NoneType' object has no attribute 'contact_list'
```

exe compile log:
http://www.megaupload.com/?d=P9GS7G7G

**Comment by Sbte** [comment]
That's most likely because you still have incomplete themes left in your config folder from before the bugs were fixed.

**Comment by mikk73** [comment]
Hi!

No, because I'm not stupid, I delete always config directory, before testing emesene2. :)

But I try again, but result is equal, no downloaded theme files if I running created exe.

Master is not changed since my last compile.

And before U ask: If I try again theme download from source with python (python emesene.py), theme download is works.

**Comment by Sbte** [comment]
Ok, that bug should be fixed in 9f1e4bdd1294480faac37f51d095805f80e2bb05

If you find any new bugs, please open new issues, because this one has gone off-topic long ago

**Comment by mikk73** [comment]
Tested, not fixed. No downloaded theme files. 

This is offtopic? And why? Theme is "plugins/theme download problems" no other. You close this topic before problem is solved.

This is offtopic:
I think waste my time here. Windows version of emesene2 is extremly buggy, unusable.
Theme/plugin download don't works, freeze/empty screen, etc
Portable version is not portable.
Installer version is bad, because I can't import emesene 1 stuff, and always ask after start emesene2 "do you want import?" But import is not success.

Of develepers need windows installation, or windows developers no other ways. This is very much time for me, and I get this message: "this is offtopic" Thanks.

**Comment by Sbte** [comment]
Of this bug it is off topic for this issue, yes. The plugin download doesn't freeze any more, as you said, which is what this issue was originally about. I'd rather have all information about one single bug in one single issue here on github. That way it's easier if we look for information about a particular bug in the future.

Also, we can't fix bugs if we don't know about them. If you keep reporting bugs (one per issue) then there is a great chance they will be fixed before the next release. So, instead of posting here, you could create a new issue for every one of them, and you'll have a greater chance that they get fixed. This issue is already closed, so no one but me will look at it.

Also, you say "tested, not fixed", but the bug you reported with the attached log is now fixed. If there is another issue, that's a new bug. Probably with new terminal output.

So, what I'm trying to say here, is that you do a very good job finding bugs, and that will greatly improve the quality of emesene, but if you want all bugs to be fixed, it's better to report them separately.
